import React, { useState } from 'react';
import { generateKundaliPDF, generateShareableReport, copyReportToClipboard } from '../utils/reportGenerator.js';

export default function ShareReport({ kundali, lifePredictions, panchang, currentDasha, name }) {
  const [status, setStatus] = useState(null); // null | 'copying' | 'copied' | 'pdf' | 'done'

  if (!kundali) return null;

  async function handleCopy() {
    setStatus('copying');
    const report = generateShareableReport(kundali, lifePredictions, panchang, currentDasha, name);
    await copyReportToClipboard(report);
    setStatus('copied');
    setTimeout(() => setStatus(null), 2500);
  }

  async function handlePDF() {
    setStatus('pdf');
    await generateKundaliPDF(kundali, lifePredictions, panchang, currentDasha, name);
    setStatus('done');
    setTimeout(() => setStatus(null), 2500);
  }

  async function handleWhatsApp() {
    const report = generateShareableReport(kundali, lifePredictions, panchang, currentDasha, name);
    const short = report.slice(0, 1000) + '\n\n...Generated by CosmicTantra V34 🕉️';
    const url = `https://wa.me/?text=${encodeURIComponent(short)}`;
    window.open(url, '_blank');
  }

  const btnBase = {
    display: 'flex', alignItems: 'center', gap: '6px',
    padding: '8px 16px', borderRadius: '20px', cursor: 'pointer',
    fontSize: '13px', fontWeight: '600', transition: 'all 0.2s',
    border: 'none', fontFamily: 'Lato, sans-serif',
  };

  return (
    <div style={{
      display: 'flex', flexWrap: 'wrap', gap: '8px', alignItems: 'center',
      padding: '1rem 1.2rem',
      background: 'rgba(255,255,255,0.03)',
      border: '1px solid rgba(124,58,237,0.2)',
      borderRadius: '12px',
    }}>
      <span style={{ color: '#9CA3AF', fontSize: '12px', letterSpacing: '0.1em', textTransform: 'uppercase', marginRight: '4px' }}>
        Share:
      </span>

      <button onClick={handleCopy} style={{
        ...btnBase,
        background: status === 'copied' ? 'rgba(16,185,129,0.2)' : 'rgba(255,255,255,0.07)',
        border: `1px solid ${status === 'copied' ? 'rgba(16,185,129,0.4)' : 'rgba(255,255,255,0.15)'}`,
        color: status === 'copied' ? '#6EE7B7' : '#E2D9F3',
      }}>
        {status === 'copying' ? '⏳' : status === 'copied' ? '✓' : '📋'}
        {status === 'copied' ? 'Copied!' : 'Copy Report'}
      </button>

      <button onClick={handlePDF} style={{
        ...btnBase,
        background: status === 'pdf' ? 'rgba(124,58,237,0.3)' : 'rgba(124,58,237,0.15)',
        border: '1px solid rgba(124,58,237,0.4)',
        color: status === 'pdf' ? '#C4B5FD' : '#A78BFA',
      }}>
        {status === 'pdf' ? '⏳ Generating...' : status === 'done' ? '✓ Saved!' : '📄 Download PDF'}
      </button>

      <button onClick={handleWhatsApp} style={{
        ...btnBase,
        background: 'rgba(37,211,102,0.12)',
        border: '1px solid rgba(37,211,102,0.3)',
        color: '#4ADE80',
      }}>
        💬 WhatsApp
      </button>
    </div>
  );
}
